---
title: "Cangrejos"
author: "Jesus Castellanos"
date: "7/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r echo=FALSE}
#getwd()
crab <- read.table("C:/Users/auscu/OneDrive/Documents/Ejercicios R/Cangrejos/datacrab.txt",
                        header = TRUE                      
)
head(crab, 5)
str(crab)

```

## Regla de la raiz cuadra de la longitud
```{r echo=FALSE}
cw = crab$width
n <- length(cw)
k1 <- ceiling(sqrt(n))
k1
```


## Regla de Sturges:
```{r echo=FALSE}
k2 = ceiling(1+log(n,2))
k2
nclass.Sturges(cw) #aplicando solo un comanod en R
```

## Regla de Scoot:
```{r echo=FALSE}
As <-3.5*sd(cw)*n^(-1/3) # Amplitud teorica
k3 <- ceiling(diff(range(cw))/As) 
k3
nclass.scott(cw) #aplicando solo un comanod en R
```

## Regla de Freedman-Diaconis
```{r echo=FALSE}
Afd = 2*(quantile(cw,0.75,names= FALSE)-quantile(cw,0.25,names = FALSE))*n^(-1/3)
k4 <- ceiling(diff(range(cw))/Afd)
k4
nclass.FD(cw) #aplicando solo un comanod en R
```

